### ISSUE TITLE
Option to restrict rating to authenticated users

### ISSUE THREAD

**Issue by MrkGrgsn** [6aika/ckanext-rating#4]
We have a client who is now using this extension, so thank you very much for creating it! It was very easy to integrate into the repository. Unfortunately I can't share the site with you as our client's repository is an internal one.

This client also wanted to restrict ratings to authenticated users.  In our [fork](https://github.com/DataShades/ckanext-rating) we have added an optional configuration option that does an authentication check in the snippets and the create action.  Are you interested in accepting a PR for this feature?

**Comment by Zharktas** [comment]
We would be gladly accept PR for it, we did not implement it originally because the instance where this extension is originally develop for, does not allow accounts for anyone whom wish to rate datasets.

**Comment by MrkGrgsn** [comment]
Great! @wildcatzita, who did most of the work, or I'll work on a PR. There are a couple of other small things that I'll run past you as I get time too.

**Comment by wildcatzita** [comment]
Hi @Zharktas. Also we have added more features to your extension:

- Authenticated users can change their rating of an dataset from within the Dataset detail page

-  Aggregate dataset rating is shown as a number of stars (1-5 in half star increments) on the Dataset detail page

- Aggregate dataset rating is shown as a number of stars (1-5 in half star increments) on Dataset tiles in search results and dataset list.

- Fixed bug where user's own rating shown in sidebar is incorrect

- Search results can be sorted by Dataset Rating, asc/desc.

Are you interested in accepting a PR for this features too and the previous feature that you discuss with @MrkGrgsn?

**Comment by Zharktas** [comment]
@wildcatzita we would gladly accept those too, half-star increments would be nice and the rest of the features are basically bugs which we haven't had time to fix :).

**Comment by wildcatzita** [comment]
Hi @Zharktas. Made [PR](https://github.com/6aika/ckanext-rating/pull/5). Can you please check? :)

**Comment by MrkGrgsn** [comment]
PRs have been merged, thanks @Zharktas, @mikkonieminen and @wildcatzita
